- name: Deploy Petclinic
  hosts: petclinic
  become: yes
  tasks:
    - name: Copy artifact
      copy:
        src: /var/lib/jenkins/workspace/17647-a2/artifact/target
        dest: /home/vagrant/17647-a2
    - name: Deploy application
      shell: java -jar -Dserver.port=80 /home/vagrant/17647-a2/target/*.jar
      # async: 10
      # poll: 0

